import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:spendwisesyncapp/providers/user_preferences_provider.dart';

class FinancialDisclaimerScreen extends ConsumerWidget {
  final VoidCallback? onAccept;

  const FinancialDisclaimerScreen({Key? key, this.onAccept}) : super(key: key);

  static const String _disclaimerText = '''FINANCIAL DISCLAIMER

SpendWise Sync is a personal finance tracking and planning tool designed to help you manage your expenses, set budgets, and organize your financial information.

IMPORTANT: The information, predictions, insights, and recommendations provided by SpendWise Sync are for informational purposes only and should NOT be considered as professional financial, investment, tax, or legal advice.

⚠️  LIMITATIONS AND DISCLAIMERS:

1. NO PROFESSIONAL ADVICE: SpendWise Sync does not provide financial advisory services. Any insights, predictions, or suggestions generated by the app's AI are estimates based on your data and should not replace consultation with a qualified financial professional.

2. ACCURACY: While we strive for accuracy, SpendWise Sync makes no guarantee regarding the accuracy, completeness, or reliability of spending predictions, budget projections, or financial insights.

3. THIRD-PARTY SERVICES: SpendWise Sync integrates with third-party services (Firebase, Google APIs). We are not responsible for their availability, accuracy, or security issues.

4. PERSONAL RESPONSIBILITY: You are solely responsible for verifying information provided by the app before making any financial decisions.

5. NO LIABILITY: SpendWise Sync, its developers, and associated parties are not liable for any financial loss, damages, or consequences resulting from reliance on app-provided information.

6. TAX & LEGAL MATTERS: For tax preparation, legal advice, investment decisions, or complex financial matters, consult with:
   • A certified financial advisor
   • A certified public accountant (CPA)
   • A tax professional
   • An attorney

7. DATA SECURITY: While we implement security measures, no online system is 100% secure. Protect your login credentials and review your account regularly.

By accepting this disclaimer, you acknowledge that you have read, understood, and agree to its terms.''';

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isDark =
        Theme.of(context).brightness == Brightness.dark;

    final bgColor = isDark ? const Color(0xFF0f1115) : const Color(0xFFf6f7f8);
    final cardColor = isDark ? const Color(0xFF1a1d24) : Colors.white;
    final borderColor = isDark ? const Color(0xFF2d3542) : const Color(0xFFe2e8f0);
    final textLight = isDark ? const Color(0xFFd1d5db) : const Color(0xFF0f172a);
    final textGrey = isDark ? const Color(0xFF94a3b8) : const Color(0xFF64748b);
    final primary = const Color(0xFF00d4ff);
    const redError = Color(0xFFef4444);

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        backgroundColor: bgColor,
        elevation: 0,
        title: Text(
          'Financial Disclaimer',
          style: TextStyle(
            color: textLight,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.close, color: textLight),
            onPressed: () => Navigator.pop(context),
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(20),
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: cardColor,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: borderColor),
                ),
                child: Text(
                  _disclaimerText,
                  style: TextStyle(
                    color: textGrey,
                    fontSize: 13,
                    height: 1.6,
                    fontFamily: 'Courier',
                  ),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Warning banner
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: redError.withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: redError.withValues(alpha: 0.3),
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(Icons.warning, color: redError, size: 20),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          'Consult a professional for financial decisions',
                          style: TextStyle(
                            color: redError,
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                // Accept button
                SizedBox(
                  height: 56,
                  child: ElevatedButton(
                    onPressed: () {
                      ref
                          .read(userPreferencesProvider.notifier)
                          .acceptDisclaimer();
                      onAccept?.call();
                      Navigator.pop(context);
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: primary,
                      foregroundColor: Colors.black,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: const Text(
                      'I Accept',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class FinancialDisclaimerDialog extends ConsumerWidget {
  const FinancialDisclaimerDialog({Key? key}) : super(key: key);

  static const String _disclaimerText = '''FINANCIAL DISCLAIMER

SpendWise Sync is a personal finance tracking tool designed to help you manage your expenses and budgets.

⚠️  IMPORTANT NOTICE:

The information, predictions, and recommendations provided by SpendWise Sync are for informational purposes only and do NOT constitute professional financial, investment, tax, or legal advice.

KEY DISCLAIMERS:

• No Professional Advice: Consult a qualified financial advisor, CPA, or attorney for important decisions
• No Accuracy Guarantee: Predictions and insights are estimates based on your data
• Personal Responsibility: You are responsible for verifying information before acting
• No Liability: We are not liable for any financial losses from using this app
• Data Security: Protect your credentials; no system is 100% secure

For tax, legal, or investment matters, consult with a professional.''';

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isDark =
        Theme.of(context).brightness == Brightness.dark;

    final bgColor = isDark ? const Color(0xFF1a1d24) : Colors.white;
    final borderColor = isDark ? const Color(0xFF2d3542) : const Color(0xFFe2e8f0);
    final textLight = isDark ? const Color(0xFFd1d5db) : const Color(0xFF0f172a);
    final textGrey = isDark ? const Color(0xFF94a3b8) : const Color(0xFF64748b);
    final primary = const Color(0xFF00d4ff);
    const redError = Color(0xFFef4444);

    return Dialog(
      backgroundColor: bgColor,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(24),
        side: BorderSide(color: borderColor),
      ),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header with close button
            Padding(
              padding: const EdgeInsets.all(20),
              child: Row(
                children: [
                  Icon(Icons.info_outline, color: primary, size: 24),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Financial Disclaimer',
                      style: TextStyle(
                        color: textLight,
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  IconButton(
                    icon: Icon(Icons.close, color: textGrey),
                    onPressed: () => Navigator.pop(context),
                    padding: EdgeInsets.zero,
                    constraints: const BoxConstraints(),
                  ),
                ],
              ),
            ),
            Divider(color: borderColor, height: 1),
            // Content
            Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    _disclaimerText,
                    style: TextStyle(
                      color: textGrey,
                      fontSize: 12,
                      height: 1.6,
                    ),
                  ),
                  const SizedBox(height: 16),
                  // Warning box
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: redError.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(
                        color: redError.withValues(alpha: 0.3),
                      ),
                    ),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Icon(Icons.warning, color: redError, size: 18),
                        const SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            'Consult a professional for financial decisions',
                            style: TextStyle(
                              color: redError,
                              fontSize: 11,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            Divider(color: borderColor, height: 1),
            // Buttons
            Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                children: [
                  Expanded(
                    child: TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: Text(
                        'View Full Text',
                        style: TextStyle(
                          color: primary,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: () {
                        ref
                            .read(userPreferencesProvider.notifier)
                            .acceptDisclaimer();
                        Navigator.pop(context);
                      },
                      style: ElevatedButton.styleFrom(
                        backgroundColor: primary,
                        foregroundColor: Colors.black,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                      child: const Text(
                        'I Accept',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
